### ISSUE TITLE
Repo transfer

### ISSUE THREAD

**Issue by nitriques** [6ui11em/multilingual_tag_field#8]
HI @6ui11em 
Can you transfer this repo to me please ? Or add me as a contributor ? I have a couple of patches I'd like to make. Thanks!

**Comment by 6ui11em** [comment]
Hi @nitriques,

I just transfered this repo. Thank you to take care of it!

**Comment by nitriques** [comment]
Thanks a lot! Do you want push access ? I'll be moving it to Deux Huit Huit.

**Comment by 6ui11em** [comment]
It’s not necessary, Thank you.

**Comment by nitriques** [comment]
Perf! Thanks again!
